#!/bin/bash
   
#Network configuration
arch-chroot /mnt <<EOF
hostname=antarctica
echo "\$hostname" > /etc/hostname
cat <<ZOF >> /etc/hosts
127.0.0.1 localhost
::1 localhost
127.0.1.1 \$hostname.localdomain \$hostname
ZOF
EOF
