#!/bin/bash
   
#Installing programming languages
arch-chroot /mnt <<EOF
programming_language_1=python
aura -S \$programming_language_1 python-pip --noconfirm
echo \$PATH | grep \\\$HOME/bin &> /dev/null
if [ \$? -ne 0 ]; then
  echo "PATH="'"'"\\\$HOME/bin:\\\$HOME/bin/python_scripts:\\\$PATH"'"'"" >> $Bashrc
fi
mkdir -p /home/$User/bin/python_scripts
EOF
