#!/bin/bash
   
#Installing spaced repetition software...
Bashrc=/home/roberts/.bashrc
arch-chroot /mnt <<EOF
spaced_repetition_software=anki-bin
install_aur_program \$spaced_repetition_software
cat <<EOT >> $Bashrc
function anki {
nohup \$spaced_repetition_software "\\\$@" > /dev/null 2>&1 & disown
}
EOT
EOF
