#!/bin/bash
   
#Chroot
arch-chroot /mnt <<EOF
text_editor=vim
aura -S \$text_editor --noconfirm
cat <<'EOT' > /home/$User/.vimrc
"I want numbers to appear before each line of text
set nu!

"Customize Vim to make it better looking
":highlight Normal ctermfg=white ctermbg=black

"Miscellaneous
syntax on
filetype plugin indent on
set autoindent
set smartindent
set expandtab "expand tabs to spaces. Essential in Python
set tabstop=2 "number of spaces tab is counted for. Can be changed to more popular 4, I prefer 2
set shiftwidth=2 "number of spaces to use for autoindent. 4 is more popular. I prefer 2
set backspace=2 "Fix backspace behaviour on most terminals
packloadall "Load all plugins
silent! helptags ALL "Load help files for all plugins
let c_no_curly_error=1

"When switching buffers, I don't want to save file all the time
set hidden

"When spliting, I want to open in the below window
set splitbelow

"When vertically spliting, I want to open in the right window
set splitright

"Fast split navigation with <ctrl> + hjkl (instead of default <ctrl> + w and
"then hjkl
noremap <c-h> <c-w><c-h>
noremap <c-j> <c-w><c-j>
noremap <c-k> <c-w><c-k>
noremap <c-l> <c-w><c-l>
noremap <c-H> <c-w><c-H>

"vim not typing ā, ū, ē etc. The next 3 lines fix that
set enc=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf8,prc

"I want terminal to open bottom not top
cabbrev bt bo term
cabbrev ua tabnew

"I don't want to type set nu or set nu! all the time
cabbrev snn set nu
cabbrev ss set nu!

"Terminal ctrl+hjkl doesn't work. I want that it does work
tnoremap <c-j> <c-w><c-j>
tnoremap <c-k> <c-w><c-k>
tnoremap <c-l> <c-w><c-l>
tnoremap <c-h> <c-w><c-h>

"When searching with / and n I do not want to hit the beginning again. I want it to stop the search. The reason for this is the macros
set nowrapscan

"I select certain lines with v,V (visual), press zf, and lines get folded. zo opens the fold. zd deletes the fold
set foldmethod=manual

"make tab completion the same as in Bash
set wildmenu
set wildmode=list:longest

"If I create folds and then close the file and then reopen the file, the folds have automatically opened. I don't want that
augroup AutoSaveFolds
autocmd!
autocmd BufWinLeave ?* mkview
autocmd BufWinEnter ?* silent loadview
augroup END

"I hate dark mode. I want to not have dark mode
:colorscheme morning
EOT
echo 'alias vi=vim' >> $Bashrc
EOF
