#!/bin/bash
   
#Install software which downloads videos from youtube
arch-chroot /mnt <<EOF
software_that_downloads_videos_from_youtube=youtube-dl
useradd -m nobodyyyy
echo '%nobodyyyy ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
su - nobodyyyy -c "sudo aura -A \$software_that_downloads_videos_from_youtube --noconfirm; echo \\\$? > /tmp/was_program_installed.txt"
userdel -f nobodyyyy
rm -rf /home/nobodyyyy
sed -i '/nobodyyyy/d' /etc/sudoers
Errorr=\$(cat /tmp/was_program_installed.txt)
if [ \$Errorr -ne 0 ]; then
  useradd -m nobodyyyy
  echo '%nobodyyyy ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
su - nobodyyyy <<HERE
sudo aura -A \$software_that_downloads_videos_from_youtube --noconfirm &> errors.txt
public_key=\\\$(grep 'unknown public key' errors.txt | sed 's/^.*\(unknown public key\)/\1/' | gawk '{print \\\$4}' | sed 's/)$//')
echo \\\$public_key
gpg --recv-keys \\\$public_key
echo \\\$?
sudo aura -A \$software_that_downloads_videos_from_youtube --noconfirm
HERE
  sed -i '/nobodyyyy/d' /etc/sudoers
  userdel -f nobodyyyy
  rm -rf /home/nobodyyyy
fi
echo 'alias yd="youtube-dl"' >> $Bashrc
echo 'alias ydx="youtube-dl -x"' >> $Bashrc
EOF
