#!/bin/bash
   
#Installing software for battery power thermal readings...
arch-chroot /mnt <<EOF
software_for_battery_power_thermal_readings=acpi
pacman -S \$software_for_battery_power_thermal_readings --noconfirm
echo 'alias ac="acpi"' >> $Bashrc
EOF
