#!/bin/bash
   
#Installing setclip...
arch-chroot /mnt <<EOF
aura -S xclip --noconfirm
echo 'alias setclip="xclip -selection c"' >> $Bashrc
cat <<'EOT'>> $Bashrc
function c {
  echo "\$1" | setclip
}
EOT
EOF
