#!/bin/bash
   
#Install password manager
arch-chroot /mnt <<EOF
password_manager=pass
aura -S \$password_manager --noconfirm
echo 'alias gen="pass generate -c \$1 \$2"' >> $Bashrc
echo 'alias epa="pass -c Email/roberts.ziedins@tutanota.com"' >> $Bashrc
echo 'alias epar="c '"'"'roberts.ziedins@tutanota.com'"'"'"' >> $Bashrc
EOF
