#!/bin/bash
   
#Installing messanger...
arch-chroot /mnt <<EOF
messanger=signal-desktop
pacman -S \$messanger --noconfirm
cat <<'EOT' >> $Bashrc
function syg {
  nohup signal-desktop "\$@" > /dev/null 2>&1 & disown
}
EOT
EOF
