#!/bin/bash
   
#Install window manager
arch-chroot /mnt <<EOF
window_manager=ratpoison
install_aur_program \$window_manager
cat <<ZOF > /home/$User/.ratpoisonrc
# Setting the escape key to the Windows key
escape Super_L

# Make Alt-Tab movement (Super Super still does not work unfortunately)
definekey top M-Tab other
definekey root z other

# Make banish happen automatically each time windows are changed
addhook switchwin banish
ZOF
#Order X11 to start ratpoison once X11 has been launched
echo 'exec /usr/bin/ratpoison' >> /home/$User/.xinitrc
EOF
