#!/bin/bash
   
#Installing software which downloads videos from youtube...
arch-chroot /mnt <<EOF
software_that_downloads_videos_from_youtube=youtube-dl
install_aur_program \$software_that_downloads_videos_from_youtube
echo 'alias yd="youtube-dl"' >> $Bashrc
echo 'alias ydx="youtube-dl -x"' >> $Bashrc
EOF
