#!/bin/bash
   
#Install terminal emulator
arch-chroot /mnt <<EOF
terminal_emulator=xterm
aura -S \$terminal_emulator --noconfirm
cat <<EOZ > /home/$User/.Xresources
XTerm.termName: xterm-256color
XTerm.vt100.locale: false
XTerm.vt100.utf8: true
XTerm.vt100.saveLines: 4096
XTerm*faceName: Dejavu Sans Mono
XTerm*faceSize: 14 
XTerm*foreground: black
XTerm*background: white
XTerm*pointerColor: black
XTerm*pointerColorBackground: black
XTerm*cursorColor: white
XTerm*pointerShape: SHAPE
XTerm*highlightSelection: true
XTerm*trimSelection: true
<Btn1Up>: select-end(PRIMARY, CLIPBOARD, CUT_BUFFER0),\n\
<Btn2Up>: insert-selection(PRIMARY)
XTerm*selectToClipboard: true
XTerm*allowBoldFonts: false
EOZ
EOF
