#!/bin/bash
   
#Install sound
arch-chroot /mnt <<EOF
pacman -S alsa-utils pulseaudio pavucontrol --noconfirm
install_aur_program apulse
usermod -aG audio $User
amixer set Speaker unmute
amixer set Master unmute
amixer set Master 100%
amixer set Speaker 100%
echo 'alias am="alsamixer"' >> $Bashrc
EOF
