#!/bin/bash
   
#Installing SSH client...
arch-chroot /mnt <<EOF
pacman -S openssh --noconfirm
cd /home/$User
git clone https://github.com/ccontavalli/ssh-ident.git
cd ssh-ident
cp ssh-ident /usr/bin
echo 'alias ssh="/usr/bin/ssh-ident"' >> $Bashrc
echo 'alias scp="scp -S /usr/bin/ssh-ident"' >> $Bashrc
EOF
