#!/bin/bash
   
#Installing hypervisor...
arch-chroot /mnt <<EOF
hypervisor=virtualbox
pacman -S \$hypervisor --noconfirm
cat <<'EOT' >> $Bashrc
function vm {
  nohup virtualbox "\$@" > /dev/null 2>&1 & disown
}
EOT
EOF
