#!/bin/bash
   
#Installing notify-send...
arch-chroot /mnt <<EOF
pacman -S libnotify notification-daemon --noconfirm
sed -i '\$i\/usr/lib/notification-daemon-1.0/notification-daemon &' /home/$User/.xinitrc
EOF
