#!/bin/bash
   
#Mirror is server from which everything will be downloaded
#I want to have mirrors from my country (Latvia) or neighouring country (Lithuania). This way, downloading will happen faster
#Selecting mirrors...
reflector --protocol 'https,http' --country 'Latvia,Lithuania,Estonia,Finland,Poland' --latest 10 --fastest 10 --sort rate --save /etc/pacman.d/mirrorlist
