#!/bin/bash
   
#Select mirrors
#Mirror is server from which everything will be downloaded
#I want to have mirrors from my country (Latvia) or neighouring country (Lithuania). This way, downloading will happen faster
#cat <<'EOF' > /tmp/mirrors
#Server = https://archlinux.koyanet.lv/archlinux/$repo/os/$arch
#Server = http://archlinux.koyanet.lv/archlinux/$repo/os/$arch
#Server = https://mirrors.atviras.lt/archlinux/$repo/os/$arch
#Server = https://mirrors.ims.nksc.lt/archlinux/$repo/os/$arch
#Server = http://mirrors.ims.nksc.lt/archlinux/$repo/os/$arch
#Server = http://mirrors.atviras.lt/archlinux/$repo/os/$arch
#EOF
#sed -i '1r /tmp/mirrors' /etc/pacman.d/mirrorlist
reflector --protocol 'https,http' --country 'Latvia,Lithuania,Estonia,Finland,Poland' --latest 10 --fastest 10 --sort rate --save /etc/pacman.d/mirrorlist
